<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-16T22:15:15 IST" name="Default suite" finished-at="2022-11-16T22:15:32 IST" duration-ms="17375">
    <groups>
    </groups>
    <test started-at="2022-11-16T22:15:15 IST" name="Default test" finished-at="2022-11-16T22:15:32 IST" duration-ms="17375">
      <class name="Test_Class.Upstox_TestCase6">
        <test-method is-config="true" signature="browseropen()[pri:0, instance:Test_Class.Upstox_TestCase6@55183b20]" started-at="2022-11-16T22:15:15 IST" name="browseropen" finished-at="2022-11-16T22:15:18 IST" duration-ms="3551" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browseropen -->
        <test-method is-config="true" signature="logintoapp()[pri:0, instance:Test_Class.Upstox_TestCase6@55183b20]" started-at="2022-11-16T22:15:18 IST" name="logintoapp" finished-at="2022-11-16T22:15:28 IST" duration-ms="9943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintoapp -->
        <test-method signature="verifyUN()[pri:0, instance:Test_Class.Upstox_TestCase6@55183b20]" started-at="2022-11-16T22:15:28 IST" name="verifyUN" finished-at="2022-11-16T22:15:28 IST" duration-ms="138" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [Harshad R.] but found [Harshad R.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [Harshad R.] but found [Harshad R.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at org.testng.Assert.assertNotEquals(Assert.java:2055)
at Test_Class.Upstox_TestCase6.verifyUN(Upstox_TestCase6.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUN -->
        <test-method is-config="true" signature="logouttoapp(org.testng.ITestResult)[pri:0, instance:Test_Class.Upstox_TestCase6@55183b20]" started-at="2022-11-16T22:15:28 IST" name="logouttoapp" finished-at="2022-11-16T22:15:32 IST" duration-ms="3676" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUN status=FAILURE method=Upstox_TestCase6.verifyUN()[pri:0, instance:Test_Class.Upstox_TestCase6@55183b20] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logouttoapp -->
        <test-method is-config="true" signature="browserclose()[pri:0, instance:Test_Class.Upstox_TestCase6@55183b20]" started-at="2022-11-16T22:15:32 IST" name="browserclose" finished-at="2022-11-16T22:15:32 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserclose -->
      </class> <!-- Test_Class.Upstox_TestCase6 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
